name: Robot Framework Test Run

# defines triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# way of restricting the default token’s access
permissions:
  contents: write # required to push to gh-pages

# groups tasks
jobs:
  build:
    # specifies the OS runner
    runs-on: ubuntu-latest
    # run the same job across multiple configurations
    strategy:
      matrix:
        # run test in multiple browser
        browser: [chrome, firefox]
        # ensures your workflow runs on multiple Python versions automatically
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: 📥 Checkout Repository
      # pulls your repo code into the runner
      uses: actions/checkout@v4
    #   with:
    #       # fetches the entire Git history
    #       fetch-depth: 0

    - name: 🔄 Check if Branch is up-to-date
      run: |
        git fetch origin ${{ github.base_ref }}
        LOCAL=$(git rev-parse HEAD)
        REMOTE=$(git rev-parse origin/${{ github.base_ref }})
        if [ "$LOCAL" != "$REMOTE" ]; then
          echo "❌ Branch is not up to date with origin/${{ github.base_ref }}. Please run git pull."
          exit 1
        else
          echo "✅ Branch is up to date."
        fi

    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: 📚 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🧪 Run tests on ${{ matrix.browser }}
      run: |
        robot \
                --variable HEADLESS:True \
                --variable BROWSER:${{ matrix.browser }} \
                --outputdir results \
                .  

    - name: 📊 Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
          name: robot-reports-${{ matrix.python-version }}-${{ matrix.browser }}
          path: results/${{ matrix.browser }}